# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foursquare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foursquare

  target 'FoursquareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoursquareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'IQKeyboardManagerSwift'
pod 'SwiftyJSON'
pod 'IDMPhotoBrowser'

end
